#Server settings
server:
  port: 8086

# OracleDB connection settings
spring:
  jpa:
    hibernate.ddl-auto: create
    show-sql: true

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource

    url: jdbc:oracle:thin:@//localhost:1521/FREEPDB1
    username: vlad
    password: vladpass

    oracleucp:
      connection-pool-name: ConnectionPoolName1
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
