#Active profiles: dev, qa, stage or prod

#dev - h2 database, ddl-auto=create, port 8085
spring:
  profiles:
    active: dev

#stage - oracle database, ddl-auto=create, port 8086
#spring.profiles.active=stage
